<?php
// database/seeders/CertificationItemSeeder.php

namespace Database\Seeders;

use App\Models\CertificationCategory;
use App\Models\CertificationItem;
use Illuminate\Database\Seeder;

class CertificationItemSeeder extends Seeder
{
    public function run(): void
    {
        // Pastikan categories sudah ada
        $this->call(CertificationCategorySeeder::class);

        // Helper: ambil ID kategori berdasarkan slug
        $cat = fn (string $slug): int =>
            CertificationCategory::where('slug', $slug)->value('id');

        // ─────────────────────────────────────────────────────────────────
        // BNSP
        // ─────────────────────────────────────────────────────────────────
        $bnspItems = [
            [
                'certification_category_id' => $cat('bnsp'),
                'name'          => 'Basic Electrical Training',
                'slug'          => 'basic-electrical-training',
                'code'          => 'BNSP-EL-001',
                'issuer'        => 'BNSP',
                'level'         => 'Teknisi',
                'duration'      => '4 Hari',
                'description'   => 'Pelatihan dasar kelistrikan industri yang mencakup konsep kelistrikan, instalasi panel, sistem motor, dan keselamatan listrik sesuai standar BNSP.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Basic Electrical Knowledge',
                    'Industrial Electrical System',
                    'PLC Basic',
                    'Motor Control',
                    'Panel Installation',
                    'Instrumentation Basic',
                    'Electrical Safety',
                ],
                'requirements'  => [
                    'Lulusan SMK/D3 Teknik Elektro atau setara',
                    'Pengalaman kerja minimal 6 bulan di bidang kelistrikan (untuk level lanjutan)',
                    'Membawa pakaian kerja dan APD dasar',
                ],
                'topics'        => [
                    'Basic Electrical Knowledge',
                    'Industrial Electrical System',
                    'PLC Basic',
                    'Electrical Safety',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin', 'quota' => 15, 'status' => 'open'],
                    ['batch' => 'Batch 2', 'date' => 'Setiap Rabu',  'quota' => 15, 'status' => 'open'],
                ],
                'badge_label'   => 'BNSP',
                'badge_color'   => 'bg-blue-600',
                'icon'          => 'electric_bolt',
                'is_featured'   => true,
                'is_active'     => true,
                'order'         => 1,
            ],
            [
                'certification_category_id' => $cat('bnsp'),
                'name'          => 'Motor Control & Automation',
                'slug'          => 'motor-control-automation',
                'code'          => 'BNSP-EL-002',
                'issuer'        => 'BNSP',
                'level'         => 'Teknisi',
                'duration'      => '5 Hari',
                'description'   => 'Program sertifikasi teknisi otomasi industri yang mencakup kendali motor, PLC tingkat lanjut, dan sistem SCADA untuk lingkungan pabrik modern.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Motor Control Dasar & Lanjutan',
                    'PLC Programming (Ladder & FBD)',
                    'SCADA System & HMI',
                    'Variable Speed Drive (VSD/VFD)',
                    'Troubleshooting Sistem Otomasi',
                    'Electrical Safety',
                ],
                'requirements'  => [
                    'Lulus Basic Electrical Training atau pengalaman setara',
                    'Familiar dengan dasar-dasar PLC',
                ],
                'topics'        => [
                    'Motor Control',
                    'PLC Advanced',
                    'SCADA System',
                    'Electrical Safety',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Selasa', 'quota' => 12, 'status' => 'open'],
                ],
                'badge_label'   => 'BNSP',
                'badge_color'   => 'bg-blue-600',
                'icon'          => 'settings_motion_mode',
                'is_featured'   => false,
                'is_active'     => true,
                'order'         => 2,
            ],
            [
                'certification_category_id' => $cat('bnsp'),
                'name'          => 'Operator Produksi Industri',
                'slug'          => 'operator-produksi-industri-bnsp',
                'code'          => 'BNSP-OP-001',
                'issuer'        => 'BNSP',
                'level'         => 'Operator',
                'duration'      => '5 Hari',
                'description'   => 'Sertifikasi kompetensi operator produksi industri sesuai SKKNI. Peserta diuji kemampuan mengoperasikan mesin, prosedur K3, dan pengendalian kualitas dasar.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'SKKNI Operator Produksi Industri',
                    'Pengoperasian Mesin Produksi',
                    'Prosedur K3 di Area Produksi',
                    'Quality Control Dasar',
                    'Budaya 5S / 5R',
                    'Asesmen & Uji Kompetensi',
                ],
                'requirements'  => [
                    'Lulusan SMK Teknik atau sederajat',
                    'Usia minimal 18 tahun',
                ],
                'topics'        => [
                    'SKKNI Operator Industri',
                    'Praktik Produksi Terpadu',
                    'Asesmen & Uji Kompetensi',
                    'Quality Control Dasar',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin',  'quota' => 20, 'status' => 'open'],
                    ['batch' => 'Batch 2', 'date' => 'Setiap Kamis',  'quota' => 20, 'status' => 'open'],
                ],
                'badge_label'   => 'BNSP',
                'badge_color'   => 'bg-blue-600',
                'icon'          => 'precision_manufacturing',
                'is_featured'   => true,
                'is_active'     => true,
                'order'         => 3,
            ],
            [
                'certification_category_id' => $cat('bnsp'),
                'name'          => 'Teknisi Instrumentasi Industri',
                'slug'          => 'teknisi-instrumentasi-industri',
                'code'          => 'BNSP-IN-001',
                'issuer'        => 'BNSP',
                'level'         => 'Teknisi',
                'duration'      => '7 Hari',
                'description'   => 'Program sertifikasi teknisi instrumentasi yang mencakup kalibrasi alat ukur, loop checking, commissioning, dan pemeliharaan sistem instrumentasi proses industri.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Dasar-Dasar Instrumentasi Proses',
                    'Sensor & Transduser Industri',
                    'Kalibrasi Alat Ukur (Tekanan, Suhu, Flow)',
                    'Loop Checking & Commissioning',
                    'Distributed Control System (DCS) Dasar',
                    'Pemeliharaan Instrumen Preventif',
                    'Safety Instrumented System (SIS)',
                ],
                'requirements'  => [
                    'Lulusan D3/S1 Teknik Instrumentasi atau Elektro',
                    'Pengalaman kerja di bidang instrumentasi diutamakan',
                ],
                'topics'        => [
                    'PLC Programming & SCADA',
                    'Kalibrasi Instrumen Industri',
                    'Loop Checking & Commissioning',
                    'Safety Instrumented System',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin',  'quota' => 10, 'status' => 'open'],
                ],
                'badge_label'   => 'BNSP',
                'badge_color'   => 'bg-blue-600',
                'icon'          => 'electrical_services',
                'is_featured'   => false,
                'is_active'     => true,
                'order'         => 4,
            ],
            [
                'certification_category_id' => $cat('bnsp'),
                'name'          => 'Authorized Gas Tester (AGT)',
                'slug'          => 'authorized-gas-tester',
                'code'          => 'BNSP-GT-001',
                'issuer'        => 'LSP Promigas',
                'level'         => 'Spesialis',
                'duration'      => '3 Hari',
                'description'   => 'Sertifikasi petugas penguji gas berbahaya di area confined space dan lingkungan kerja berisiko tinggi. Wajib bagi pekerja MIGAS, petrokimia, dan industri pengolahan.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Pengenalan Gas Berbahaya & Sifatnya',
                    'Deteksi Gas: Peralatan & Prosedur',
                    'Confined Space Entry & Gas Testing',
                    'H2S Safety & SCBA',
                    'Interpretasi Hasil Pengukuran Gas',
                    'Emergency Response Prosedur',
                ],
                'requirements'  => [
                    'Bekerja di lingkungan MIGAS, petrokimia, atau industri proses',
                    'Memahami dasar-dasar K3 industri',
                ],
                'topics'        => [
                    'Gas Detection',
                    'Confined Space',
                    'H2S Safety',
                    'Emergency Response',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Rabu', 'quota' => 15, 'status' => 'open'],
                ],
                'badge_label'   => 'LSP Promigas',
                'badge_color'   => 'bg-amber-600',
                'icon'          => 'air',
                'is_featured'   => false,
                'is_active'     => true,
                'order'         => 5,
            ],
            [
                'certification_category_id' => $cat('bnsp'),
                'name'          => 'Welder SMAW 3G / 4G',
                'slug'          => 'welder-smaw-3g-4g',
                'code'          => 'BNSP-WD-001',
                'issuer'        => 'BNSP',
                'level'         => 'Teknisi',
                'duration'      => '21 Hari',
                'description'   => 'Sertifikasi juru las SMAW posisi 3G (vertikal) dan 4G (overhead) sesuai standar BNSP, AWS D1.1, dan ASME Section IX untuk industri konstruksi dan manufaktur.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Teori Dasar Pengelasan & Metalurgi Las',
                    'Keselamatan Kerja Pengelasan',
                    'Teknik SMAW Posisi 1G & 2G',
                    'Teknik SMAW Posisi 3G (Vertikal)',
                    'Teknik SMAW Posisi 4G (Overhead)',
                    'Inspeksi Visual Las & Cacat Las',
                    'Uji NDT Dasar',
                ],
                'requirements'  => [
                    'Memiliki pengalaman las dasar minimal 3 bulan',
                    'Kondisi fisik dan penglihatan baik',
                    'Membawa APD pengelasan pribadi (jika ada)',
                ],
                'topics'        => [
                    'Teknik SMAW Posisi 3G & 4G',
                    'Standar AWS D1.1 & ASME IX',
                    'NDT Visual Inspection',
                    'Welding Safety',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin (3 minggu)', 'quota' => 12, 'status' => 'open'],
                ],
                'badge_label'   => 'BNSP',
                'badge_color'   => 'bg-blue-600',
                'icon'          => 'hardware',
                'is_featured'   => true,
                'is_active'     => true,
                'order'         => 6,
            ],
        ];

        // ─────────────────────────────────────────────────────────────────
        // KEMNAKER
        // ─────────────────────────────────────────────────────────────────
        $kemnnakerItems = [
            [
                'certification_category_id' => $cat('kemnaker'),
                'name'          => 'Ahli K3 Umum',
                'slug'          => 'ahli-k3-umum',
                'code'          => 'KMK-K3-001',
                'issuer'        => 'Kemnaker RI',
                'level'         => 'Profesional',
                'duration'      => '12 Hari',
                'description'   => 'Program sertifikasi Ahli K3 Umum resmi Kementerian Ketenagakerjaan RI. Peserta memahami perundangan K3, manajemen risiko, inspeksi, audit, dan penyelidikan kecelakaan kerja.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Perundangan K3 Indonesia & Dasar Hukum',
                    'Manajemen Risiko & HIRA',
                    'Sistem Manajemen K3 (SMK3)',
                    'Inspeksi & Audit K3',
                    'Investigasi Kecelakaan Kerja',
                    'K3 Konstruksi & Kebakaran',
                    'K3 Listrik & Pesawat Uap',
                    'Presentasi & Pembuatan Laporan K3',
                ],
                'requirements'  => [
                    'Pendidikan minimal D3 semua jurusan',
                    'Bekerja atau berencana berkarir di bidang K3/HSE',
                ],
                'topics'        => [
                    'Perundangan K3',
                    'Manajemen Risiko',
                    'Inspeksi K3',
                    'Audit SMK3',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin (2 minggu)', 'quota' => 25, 'status' => 'open'],
                    ['batch' => 'Batch 2', 'date' => 'Setiap Senin (2 minggu)', 'quota' => 25, 'status' => 'open'],
                ],
                'badge_label'   => 'Kemnaker RI',
                'badge_color'   => 'bg-green-700',
                'icon'          => 'health_and_safety',
                'is_featured'   => true,
                'is_active'     => true,
                'order'         => 1,
            ],
            [
                'certification_category_id' => $cat('kemnaker'),
                'name'          => 'Operator Forklift',
                'slug'          => 'operator-forklift',
                'code'          => 'KMK-FK-001',
                'issuer'        => 'Kemnaker RI',
                'level'         => 'Operator',
                'duration'      => '3 Hari',
                'description'   => 'Sertifikasi resmi operator forklift dari Kemnaker RI. Peserta dilatih teknik pengoperasian aman, perawatan harian, dan prosedur keselamatan forklift industri.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Mengenal Forklift: Jenis & Komponen',
                    'Pre-operation Inspection',
                    'Teknik Pengoperasian Forklift yang Aman',
                    'Load Handling & Stacking',
                    'Peraturan Lalu Lintas di Dalam Pabrik',
                    'Perawatan Harian & Troubleshooting Dasar',
                ],
                'requirements'  => [
                    'Usia minimal 18 tahun',
                    'Memiliki SIM A atau C yang masih berlaku',
                    'Kondisi fisik dan penglihatan baik',
                ],
                'topics'        => [
                    'Pre-operation Inspection',
                    'Teknik Pengoperasian Aman',
                    'Load Handling & Stacking',
                    'Perawatan Harian Forklift',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin', 'quota' => 15, 'status' => 'open'],
                    ['batch' => 'Batch 2', 'date' => 'Setiap Kamis', 'quota' => 15, 'status' => 'open'],
                ],
                'badge_label'   => 'Kemnaker RI',
                'badge_color'   => 'bg-green-700',
                'icon'          => 'forklift',
                'is_featured'   => false,
                'is_active'     => true,
                'order'         => 2,
            ],
            [
                'certification_category_id' => $cat('kemnaker'),
                'name'          => 'Operator Overhead Crane',
                'slug'          => 'operator-overhead-crane',
                'code'          => 'KMK-CR-001',
                'issuer'        => 'Kemnaker RI',
                'level'         => 'Operator',
                'duration'      => '3 Hari',
                'description'   => 'Sertifikasi operator overhead crane & bridge crane dari Kemnaker RI untuk industri manufaktur, galangan kapal, dan konstruksi berat.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Pengenalan Pesawat Angkat & Angkut',
                    'Komponen & Kapasitas Overhead Crane',
                    'Pre-use Inspection Overhead Crane',
                    'Teknik Pengoperasian & Load Calculation',
                    'Komunikasi Rigger & Operator',
                    'Perawatan & Pemeliharaan Crane',
                ],
                'requirements'  => [
                    'Usia minimal 18 tahun',
                    'Kondisi kesehatan dan penglihatan baik',
                    'Tidak memiliki riwayat vertigo',
                ],
                'topics'        => [
                    'Pre-use Inspection Overhead Crane',
                    'Teknik Pengoperasian Aman',
                    'Load Calculation',
                    'Komunikasi Rigger & Operator',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Selasa', 'quota' => 12, 'status' => 'open'],
                ],
                'badge_label'   => 'Kemnaker RI',
                'badge_color'   => 'bg-green-700',
                'icon'          => 'settings_overscan',
                'is_featured'   => false,
                'is_active'     => true,
                'order'         => 3,
            ],
            [
                'certification_category_id' => $cat('kemnaker'),
                'name'          => 'Teknisi K3 Listrik',
                'slug'          => 'teknisi-k3-listrik',
                'code'          => 'KMK-EL-001',
                'issuer'        => 'Kemnaker RI',
                'level'         => 'Teknisi',
                'duration'      => '5 Hari',
                'description'   => 'Sertifikasi Teknisi K3 Listrik Kemnaker RI. Peserta memahami regulasi keselamatan listrik, inspeksi instalasi, prosedur LOTO, dan penanganan kedaruratan listrik.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Peraturan K3 Kelistrikan di Indonesia',
                    'Bahaya Listrik & Proteksi Diri',
                    'Lockout/Tagout (LOTO) Prosedur',
                    'Inspeksi Instalasi Listrik',
                    'Grounding & Bonding',
                    'Arc Flash Safety',
                    'Penanganan Kedaruratan Listrik',
                ],
                'requirements'  => [
                    'Lulusan SMK/D3 Teknik Elektro atau setara',
                    'Bekerja di bidang kelistrikan industri',
                ],
                'topics'        => [
                    'Peraturan K3 Kelistrikan',
                    'Bahaya Listrik & Proteksi Diri',
                    'Lockout/Tagout (LOTO)',
                    'Arc Flash Safety',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin', 'quota' => 15, 'status' => 'open'],
                ],
                'badge_label'   => 'Kemnaker RI',
                'badge_color'   => 'bg-green-700',
                'icon'          => 'bolt',
                'is_featured'   => false,
                'is_active'     => true,
                'order'         => 4,
            ],
        ];

        // ─────────────────────────────────────────────────────────────────
        // KPDM – Oil & Gas Explosives Technician
        // ─────────────────────────────────────────────────────────────────
        $kpdmItems = [
            [
                'certification_category_id' => $cat('kpdm-oil-gas'),
                'name'          => 'KPDM – Perforating Gun Loading',
                'slug'          => 'kpdm-perforating-gun-loading',
                'code'          => 'KPDM-OG-001',
                'issuer'        => 'Kementerian ESDM RI',
                'level'         => 'Spesialis',
                'duration'      => '5 Hari',
                'description'   => 'Sertifikasi resmi Kementerian ESDM untuk teknisi perakitan dan penanganan perforating gun di operasi pengeboran dan komplesi sumur minyak dan gas bumi.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Regulasi Bahan Peledak Migas (Permen ESDM)',
                    'Pengenalan Perforating Gun & Komponen',
                    'Prosedur Perakitan Perforating Gun',
                    'Penanganan & Penyimpanan Bahan Peledak',
                    'Prosedur Keselamatan di Lokasi Pengeboran',
                    'Emergency Response & Misfire Procedure',
                    'Dokumentasi & Pelaporan',
                ],
                'requirements'  => [
                    'Bekerja di perusahaan jasa pengeboran atau perforating',
                    'Lulusan D3/S1 Teknik atau pengalaman lapangan migas',
                    'Medical fit untuk bekerja di lokasi migas',
                ],
                'topics'        => [
                    'Regulasi Bahan Peledak Migas',
                    'Prosedur Perforating Aman',
                    'Penanganan & Penyimpanan Bahan Peledak',
                    'Emergency Response KPDM',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin', 'quota' => 10, 'status' => 'open'],
                ],
                'badge_label'   => 'ESDM RI',
                'badge_color'   => 'bg-amber-700',
                'icon'          => 'oil_barrel',
                'is_featured'   => true,
                'is_active'     => true,
                'order'         => 1,
            ],
            [
                'certification_category_id' => $cat('kpdm-oil-gas'),
                'name'          => 'KPDM – Wireline Explosive Technician',
                'slug'          => 'kpdm-wireline-explosive',
                'code'          => 'KPDM-OG-002',
                'issuer'        => 'Kementerian ESDM RI',
                'level'         => 'Spesialis',
                'duration'      => '5 Hari',
                'description'   => 'Sertifikasi teknisi bahan peledak untuk operasi wireline di sumur minyak dan gas. Mencakup penggunaan detonator, penanganan peledak, dan prosedur keselamatan wireline.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Regulasi Wireline & Bahan Peledak',
                    'Peralatan Wireline & Explosive',
                    'Prosedur Operasi Wireline di Sumur',
                    'Penanganan Detonator & Initiating System',
                    'Well Control Awareness untuk Wireline',
                    'Emergency Response Wireline',
                ],
                'requirements'  => [
                    'Bekerja di perusahaan wireline services',
                    'Memiliki pengalaman lapangan migas minimal 1 tahun',
                ],
                'topics'        => [
                    'Regulasi Wireline & Bahan Peledak',
                    'Prosedur Operasi Wireline',
                    'Penanganan Detonator',
                    'Well Control Awareness',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin', 'quota' => 10, 'status' => 'open'],
                ],
                'badge_label'   => 'ESDM RI',
                'badge_color'   => 'bg-amber-700',
                'icon'          => 'cable',
                'is_featured'   => false,
                'is_active'     => true,
                'order'         => 2,
            ],
        ];

        // ─────────────────────────────────────────────────────────────────
        // Scaffolding, Working at Heights & Rigging
        // ─────────────────────────────────────────────────────────────────
        $scaffoldingItems = [
            [
                'certification_category_id' => $cat('scaffolding-heights-rigging'),
                'name'          => 'Operator Scaffolding',
                'slug'          => 'operator-scaffolding',
                'code'          => 'BNSP-SC-001',
                'issuer'        => 'BNSP & Kemnaker',
                'level'         => 'Operator',
                'duration'      => '5 Hari',
                'description'   => 'Sertifikasi operator pemasangan perancah (scaffolding) dari BNSP dan Kemnaker RI. Peserta dilatih teknik instalasi, inspeksi, dan prosedur pembongkaran perancah yang aman.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Pengenalan Scaffolding & Jenis Perancah',
                    'Komponen & Material Scaffolding',
                    'Teknik Pemasangan & Pembongkaran',
                    'Inspeksi Scaffolding Harian & Periodik',
                    'Working at Heights & Fall Protection',
                    'Peraturan K3 Scaffolding',
                    'Praktik Lapangan',
                ],
                'requirements'  => [
                    'Usia minimal 18 tahun',
                    'Kondisi fisik prima dan tidak takut ketinggian',
                    'Lulus medical check-up untuk ketinggian',
                ],
                'topics'        => [
                    'Instalasi Perancah',
                    'Inspeksi Scaffolding',
                    'Working at Heights',
                    'Fall Protection',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin', 'quota' => 15, 'status' => 'open'],
                    ['batch' => 'Batch 2', 'date' => 'Setiap Kamis', 'quota' => 15, 'status' => 'open'],
                ],
                'badge_label'   => 'BNSP & Kemnaker',
                'badge_color'   => 'bg-primary',
                'icon'          => 'architecture',
                'is_featured'   => true,
                'is_active'     => true,
                'order'         => 1,
            ],
            [
                'certification_category_id' => $cat('scaffolding-heights-rigging'),
                'name'          => 'Pengawas Scaffolding',
                'slug'          => 'pengawas-scaffolding',
                'code'          => 'BNSP-SC-002',
                'issuer'        => 'BNSP & Kemnaker',
                'level'         => 'Supervisor',
                'duration'      => '5 Hari',
                'description'   => 'Sertifikasi pengawas scaffolding untuk memimpin tim pemasangan perancah, melakukan inspeksi komprehensif, dan memastikan kepatuhan K3 di area scaffolding.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Tanggung Jawab Pengawas Scaffolding',
                    'Scaffold Design & Load Calculation',
                    'Supervisi Pemasangan & Pembongkaran',
                    'Prosedur Inspeksi & Sertifikasi Scaffolding',
                    'Manajemen Risiko Ketinggian',
                    'Emergency Response di Ketinggian',
                ],
                'requirements'  => [
                    'Lulus Sertifikasi Operator Scaffolding',
                    'Pengalaman kerja scaffolding minimal 1 tahun',
                ],
                'topics'        => [
                    'Supervisi Pemasangan Scaffolding',
                    'Scaffold Design & Load Calculation',
                    'Prosedur Inspeksi Komprehensif',
                    'Manajemen Risiko Ketinggian',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Selasa', 'quota' => 12, 'status' => 'open'],
                ],
                'badge_label'   => 'BNSP & Kemnaker',
                'badge_color'   => 'bg-primary',
                'icon'          => 'supervisor_account',
                'is_featured'   => false,
                'is_active'     => true,
                'order'         => 2,
            ],
            [
                'certification_category_id' => $cat('scaffolding-heights-rigging'),
                'name'          => 'Bekerja di Ketinggian Level 1 & 2',
                'slug'          => 'bekerja-di-ketinggian',
                'code'          => 'KMK-WH-001',
                'issuer'        => 'Kemnaker RI',
                'level'         => 'Operator',
                'duration'      => '3 Hari',
                'description'   => 'Sertifikasi wajib bagi pekerja yang bekerja di ketinggian lebih dari 1,8 meter. Mencakup penggunaan harness, sistem fall arrest, rescue di ketinggian, dan prosedur darurat.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Regulasi Working at Heights',
                    'Bahaya & Risiko Bekerja di Ketinggian',
                    'Personal Protective Equipment (Harness, Lanyard)',
                    'Sistem Fall Arrest & Restraint',
                    'Teknik Bekerja Aman di Ketinggian',
                    'Rescue di Ketinggian (Self & Team Rescue)',
                ],
                'requirements'  => [
                    'Usia minimal 18 tahun',
                    'Lulus medical check-up untuk pekerjaan ketinggian',
                    'Tidak memiliki riwayat fobia ketinggian atau kondisi medis terkait',
                ],
                'topics'        => [
                    'Personal Protective Equipment',
                    'Sistem Fall Arrest & Restraint',
                    'Teknik Bekerja Aman di Ketinggian',
                    'Rescue di Ketinggian',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Rabu', 'quota' => 15, 'status' => 'open'],
                ],
                'badge_label'   => 'Kemnaker RI',
                'badge_color'   => 'bg-green-700',
                'icon'          => 'terrain',
                'is_featured'   => false,
                'is_active'     => true,
                'order'         => 3,
            ],
            [
                'certification_category_id' => $cat('scaffolding-heights-rigging'),
                'name'          => 'Rigger / Juru Ikat (Banksman)',
                'slug'          => 'rigger-banksman',
                'code'          => 'BNSP-RG-001',
                'issuer'        => 'BNSP',
                'level'         => 'Spesialis',
                'duration'      => '4 Hari',
                'description'   => 'Sertifikasi juru ikat dan banksman untuk operasi pengangkatan beban menggunakan crane dan alat berat. Mencakup teknik rigging, kalkulasi beban, dan koordinasi crane.',
                'thumbnail'     => null,
                'cover_image'   => null,
                'modules'       => [
                    'Pengenalan Rigging & Lifting Operations',
                    'Jenis Sling & Komponen Rigging',
                    'Load Calculation & Rigging Configuration',
                    'Teknik Pengikatan Beban (Hitches & Knots)',
                    'Komunikasi Rigger & Crane Operator',
                    'Inspeksi Alat Rigging',
                    'Rigging Plan & Lift Plan',
                ],
                'requirements'  => [
                    'Usia minimal 18 tahun',
                    'Bekerja di industri konstruksi, manufaktur, atau migas',
                    'Kondisi fisik baik',
                ],
                'topics'        => [
                    'Teknik Rigging',
                    'Angkat Beban Aman',
                    'Crane Coordination',
                    'Load Calculation',
                ],
                'schedule_info' => [
                    ['batch' => 'Batch 1', 'date' => 'Setiap Senin', 'quota' => 12, 'status' => 'open'],
                ],
                'badge_label'   => 'BNSP',
                'badge_color'   => 'bg-blue-600',
                'icon'          => 'hvac',
                'is_featured'   => false,
                'is_active'     => true,
                'order'         => 4,
            ],
        ];

        // ─────────────────────────────────────────────────────────────────
        // Seed semua item
        // ─────────────────────────────────────────────────────────────────
        $allItems = array_merge(
            $bnspItems,
            $kemnnakerItems,
            $kpdmItems,
            $scaffoldingItems
        );

        foreach ($allItems as $item) {
            CertificationItem::updateOrCreate(
                ['slug' => $item['slug']],
                $item
            );
        }

        $this->command->info('✅ CertificationItem seeded: ' . count($allItems) . ' records.');
    }
}
