<?php
// database/seeders/ProgramSeeder.php

namespace Database\Seeders;

use App\Models\Program;
use App\Models\ProgramCategory;
use Illuminate\Database\Seeder;

class ProgramSeeder extends Seeder
{
    public function run(): void
    {
        // Pastikan categories sudah ada
        $this->call(ProgramCategorySeeder::class);

        $cat = fn (string $slug) => ProgramCategory::where('slug', $slug)->value('id');

        $programs = [

            // ── MANUFAKTUR & PRODUKSI ────────────────────────────────────
            [
                'category_id'        => $cat('manufaktur-produksi'),
                'title'              => 'Operator Produksi Industri',
                'slug'               => 'operator-produksi-industri',
                'description'        => 'Pelatihan intensif mencetak operator mesin produksi yang kompeten dan memahami alur kerja standar industri terkini.',
                'description_long'   => 'Program Operator Produksi Industri STC dirancang untuk mempersiapkan tenaga kerja yang siap bekerja di lini produksi pabrik modern. Peserta akan mendapatkan pemahaman mendalam tentang proses manufaktur, pengoperasian mesin, pengendalian kualitas, serta penerapan budaya K3 dan 5S di area kerja.',
                'icon'               => 'precision_manufacturing',
                'modules'            => [
                    'Dasar-Dasar Proses Manufaktur',
                    'Keselamatan Kerja Industri (K3)',
                    'Pengoperasian Mesin Produksi',
                    'Autonomous Maintenance (AM)',
                    'Quality Control Dasar & 5S',
                    'Standar Kompetensi SKKNI',
                ],
                'learning_outcomes'  => [
                    'Mengoperasikan mesin produksi sesuai SOP industri',
                    'Menerapkan prosedur K3 di area kerja secara mandiri',
                    'Melakukan quality control dasar pada produk hasil produksi',
                    'Mengimplementasikan budaya 5S di lingkungan kerja',
                    'Lulus uji kompetensi dan mendapatkan sertifikasi BNSP',
                ],
                'target_participants' => [
                    'Fresh Graduate SMK/D3 Teknik',
                    'Operator Industri Pemula',
                    'Calon Tenaga Kerja Industri',
                    'Karyawan yang ingin upgrade kompetensi',
                ],
                'duration'           => '3 Bulan',
                'level'              => 'Operator',
                'price_display'      => 'Rp 4.500.000',
                'is_featured'        => true,
                'is_active'          => true,
                'order'              => 1,
            ],
            [
                'category_id'        => $cat('manufaktur-produksi'),
                'title'              => 'Lean Manufacturing Basic',
                'slug'               => 'lean-manufacturing-basic',
                'description'        => 'Pelajari konsep eliminasi pemborosan (waste) untuk meningkatkan efisiensi proses produksi secara keseluruhan.',
                'description_long'   => 'Lean Manufacturing adalah filosofi produksi yang berfokus pada pengurangan pemborosan di setiap tahap proses. Program ini mengajarkan 7 jenis waste, value stream mapping, kaizen, dan teknik implementasi lean di lantai produksi.',
                'icon'               => 'trending_up',
                'modules'            => [
                    'Pengenalan Lean Manufacturing & Toyota Production System',
                    '7 Pemborosan (7 Wastes) dalam Produksi',
                    'Value Stream Mapping (VSM)',
                    'Kaizen & Continuous Improvement',
                    'Just In Time (JIT) Production',
                    'Implementasi Lean di Lantai Produksi',
                ],
                'learning_outcomes'  => [
                    'Mengidentifikasi dan mengklasifikasikan jenis pemborosan di lini produksi',
                    'Membuat Value Stream Mapping proses produksi',
                    'Merancang dan melaksanakan kegiatan Kaizen',
                    'Menghitung Overall Equipment Effectiveness (OEE)',
                ],
                'target_participants' => [
                    'Supervisor & Team Leader Produksi',
                    'Engineer & Teknisi Industri',
                    'Staff Quality & Continuous Improvement',
                ],
                'duration'           => '5 Hari',
                'level'              => 'Supervisor',
                'price_display'      => 'Rp 2.800.000',
                'is_featured'        => false,
                'is_active'          => true,
                'order'              => 2,
            ],
            [
                'category_id'        => $cat('manufaktur-produksi'),
                'title'              => 'Quality Control & Assurance',
                'slug'               => 'quality-control-assurance',
                'description'        => 'Sertifikasi teknik inspeksi, pengujian, dan kontrol kualitas produk sesuai standar industri yang ketat.',
                'description_long'   => 'Program QC/QA STC membekali peserta dengan kemampuan melakukan inspeksi produk, menggunakan alat ukur, menerapkan statistical process control, dan memahami sistem manajemen mutu ISO 9001. Sangat relevan untuk industri manufaktur, otomotif, dan elektronik.',
                'icon'               => 'fact_check',
                'modules'            => [
                    'Dasar-Dasar Sistem Manajemen Mutu (ISO 9001)',
                    'Teknik Inspeksi & Penggunaan Alat Ukur',
                    'Statistical Process Control (SPC)',
                    'Analisa Akar Masalah (Root Cause Analysis)',
                    '7 QC Tools',
                    'Audit Internal Mutu',
                ],
                'learning_outcomes'  => [
                    'Melakukan inspeksi kualitas produk secara sistematis',
                    'Menggunakan alat ukur industri dengan benar',
                    'Menganalisa data kualitas menggunakan 7 QC Tools',
                    'Menyusun laporan non-conformance dan corrective action',
                ],
                'target_participants' => [
                    'Staff & Inspector QC/QA',
                    'Supervisor Produksi',
                    'Engineer Manufaktur',
                ],
                'duration'           => '2 Minggu',
                'level'              => 'Teknisi',
                'price_display'      => 'Rp 3.200.000',
                'is_featured'        => false,
                'is_active'          => true,
                'order'              => 3,
            ],
            [
                'category_id'        => $cat('manufaktur-produksi'),
                'title'              => 'Implementasi 5S di Industri',
                'slug'               => 'implementasi-5s-industri',
                'description'        => 'Panduan praktis menata area kerja untuk menciptakan lingkungan pabrik yang aman, bersih, dan produktif.',
                'description_long'   => 'Program 5S (Seiri, Seiton, Seiso, Seiketsu, Shitsuke) adalah fondasi dari budaya kerja industri yang produktif. Peserta akan belajar bagaimana merencanakan, menjalankan, dan mempertahankan program 5S secara berkelanjutan di lingkungan pabrik.',
                'icon'               => 'cleaning_services',
                'modules'            => [
                    'Filosofi & Manfaat 5S/5R',
                    'Seiri (Ringkas): Pemilahan & Penghapusan',
                    'Seiton (Rapi): Penataan Area Kerja',
                    'Seiso (Resik): Pembersihan & Inspeksi',
                    'Seiketsu & Shitsuke: Standarisasi & Pembiasaan',
                    'Audit 5S & Sustaining Program',
                ],
                'learning_outcomes'  => [
                    'Merancang dan melaksanakan program 5S di area kerja',
                    'Membuat standar visual untuk area kerja',
                    'Melakukan audit 5S secara periodik',
                    'Membangun budaya kerja yang disiplin dan teratur',
                ],
                'target_participants' => [
                    'Semua Level Karyawan',
                    'Team Leader & Supervisor',
                    'Safety Officer',
                ],
                'duration'           => '2 Hari',
                'level'              => 'Semua Level',
                'price_display'      => 'Rp 1.200.000',
                'is_featured'        => false,
                'is_active'          => true,
                'order'              => 4,
            ],

            // ── K3 & HSE ─────────────────────────────────────────────────
            [
                'category_id'        => $cat('k3-hse'),
                'title'              => 'Ahli K3 Umum (Sertifikasi Kemnaker)',
                'slug'               => 'ahli-k3-umum',
                'description'        => 'Program sertifikasi Ahli K3 Umum resmi Kementerian Ketenagakerjaan RI untuk profesional keselamatan kerja.',
                'description_long'   => 'Program Ahli K3 Umum adalah sertifikasi bergengsi di bidang Keselamatan dan Kesehatan Kerja yang diakui oleh Kementerian Ketenagakerjaan RI. Peserta akan memahami perundangan K3, manajemen risiko, inspeksi K3, audit, dan investigasi kecelakaan kerja secara mendalam.',
                'icon'               => 'health_and_safety',
                'modules'            => [
                    'Perundangan K3 Indonesia & Dasar Hukum',
                    'Manajemen Risiko & Hazard Identification',
                    'SMK3 (Sistem Manajemen K3)',
                    'Inspeksi & Audit K3',
                    'Investigasi Kecelakaan Kerja',
                    'Penulisan Laporan & Presentasi K3',
                ],
                'learning_outcomes'  => [
                    'Memahami dan menerapkan peraturan K3 di tempat kerja',
                    'Melakukan identifikasi bahaya dan penilaian risiko (HIRA)',
                    'Menyusun program K3 perusahaan yang efektif',
                    'Melaksanakan audit internal SMK3',
                    'Mendapatkan sertifikasi Ahli K3 Umum Kemnaker RI',
                ],
                'target_participants' => [
                    'Safety Officer & HSE Staff',
                    'Supervisor & Manager Produksi',
                    'HR & General Affairs',
                    'Profesional yang ingin berkarir di bidang K3',
                ],
                'duration'           => '12 Hari',
                'level'              => 'Profesional',
                'price_display'      => 'Rp 6.500.000',
                'is_featured'        => true,
                'is_active'          => true,
                'order'              => 1,
            ],
            [
                'category_id'        => $cat('k3-hse'),
                'title'              => 'Fire Fighting & Fire Safety',
                'slug'               => 'fire-fighting-safety',
                'description'        => 'Pelatihan pemadaman kebakaran, evakuasi darurat, dan manajemen tanggap darurat kebakaran di industri.',
                'description_long'   => 'Program Fire Fighting STC memberikan keterampilan praktis dalam pencegahan dan penanggulangan kebakaran di lingkungan industri. Peserta langsung berlatih menggunakan APAR, hidran, dan prosedur evakuasi di lapangan.',
                'icon'               => 'local_fire_department',
                'modules'            => [
                    'Teori Dasar Kebakaran & Segitiga Api',
                    'Klasifikasi Kebakaran & Jenis APAR',
                    'Penggunaan APAR & Hidran Industri (Praktik)',
                    'Prosedur Evakuasi Darurat',
                    'Emergency Response Plan',
                    'Simulasi Pemadaman Api (Lapangan)',
                ],
                'learning_outcomes'  => [
                    'Mengoperasikan APAR dan peralatan pemadam dengan benar',
                    'Memimpin prosedur evakuasi darurat',
                    'Menyusun Emergency Response Plan sederhana',
                    'Melakukan assessment risiko kebakaran di area kerja',
                ],
                'target_participants' => [
                    'Fire Warden & Safety Officer',
                    'Semua Karyawan Industri',
                    'Tim Tanggap Darurat Perusahaan',
                ],
                'duration'           => '3 Hari',
                'level'              => 'Operator',
                'price_display'      => 'Rp 2.200.000',
                'is_featured'        => false,
                'is_active'          => true,
                'order'              => 2,
            ],
            [
                'category_id'        => $cat('k3-hse'),
                'title'              => 'Basic First Aid (P3K)',
                'slug'               => 'basic-first-aid-p3k',
                'description'        => 'Pelatihan pertolongan pertama pada kecelakaan kerja (P3K) sesuai standar industri dan PMI.',
                'description_long'   => 'Kemampuan pertolongan pertama adalah keterampilan wajib bagi setiap pekerja industri. Program ini mengajarkan teknik penanganan luka, CPR, penanganan korban jatuh, dan prosedur rujukan ke fasilitas medis dengan metode praktik langsung.',
                'icon'               => 'medical_services',
                'modules'            => [
                    'Dasar-Dasar Pertolongan Pertama',
                    'CPR & AED (Cardiopulmonary Resuscitation)',
                    'Penanganan Luka, Patah Tulang & Perdarahan',
                    'Penanganan Korban Kecelakaan & Evakuasi',
                    'Penanganan Kedaruratan Medis di Industri',
                    'Praktik Simulasi P3K (Scenario Based)',
                ],
                'learning_outcomes'  => [
                    'Melakukan CPR dengan teknik yang benar',
                    'Menangani berbagai jenis luka dan kedaruratan medis',
                    'Menggunakan peralatan P3K standar industri',
                    'Melaksanakan prosedur evakuasi korban dengan aman',
                ],
                'target_participants' => [
                    'Petugas P3K Perusahaan',
                    'Semua Karyawan Industri',
                    'Tim HSE & Safety Officer',
                ],
                'duration'           => '3 Hari',
                'level'              => 'Operator',
                'price_display'      => 'Rp 1.800.000',
                'is_featured'        => false,
                'is_active'          => true,
                'order'              => 3,
            ],

            // ── OTOMOTIF ─────────────────────────────────────────────────
            [
                'category_id'        => $cat('teknologi-otomotif'),
                'title'              => 'Teknisi Otomotif Dasar',
                'slug'               => 'teknisi-otomotif-dasar',
                'description'        => 'Fondasi keterampilan teknisi otomotif: sistem mesin, kelistrikan dasar, dan diagnosis kendaraan konvensional.',
                'description_long'   => 'Program Teknisi Otomotif Dasar STC adalah pintu gerbang karir di industri otomotif. Peserta akan mempelajari sistem utama kendaraan secara menyeluruh, mulai dari mesin, transmisi, sistem rem, kelistrikan, hingga penggunaan alat diagnostic modern.',
                'icon'               => 'directions_car',
                'modules'            => [
                    'Dasar-Dasar Teknik Otomotif',
                    'Sistem Mesin Kendaraan (Engine System)',
                    'Sistem Transmisi & Drivetrain',
                    'Sistem Rem & Suspensi',
                    'Sistem Kelistrikan Kendaraan Dasar',
                    'Diagnostic & Troubleshooting',
                ],
                'learning_outcomes'  => [
                    'Memahami cara kerja sistem utama kendaraan bermotor',
                    'Menggunakan scan tool dan alat diagnostic otomotif',
                    'Melakukan perawatan berkala dan perbaikan dasar',
                    'Membaca wiring diagram kelistrikan kendaraan',
                ],
                'target_participants' => [
                    'Lulusan SMK Otomotif',
                    'Teknisi & Mekanik Pemula',
                    'Calon Karyawan Industri Otomotif',
                ],
                'duration'           => '2 Minggu',
                'level'              => 'Teknisi',
                'price_display'      => 'Rp 3.000.000',
                'is_featured'        => true,
                'is_active'          => true,
                'order'              => 1,
            ],
            [
                'category_id'        => $cat('teknologi-otomotif'),
                'title'              => 'Sertifikasi Teknisi EV & Hybrid',
                'slug'               => 'teknisi-ev-hybrid',
                'description'        => 'Sertifikasi teknisi kendaraan listrik (EV) dan hybrid: baterai, sistem daya, dan diagnostic EV.',
                'description_long'   => 'Seiring dengan pesatnya perkembangan kendaraan listrik di Indonesia, program ini hadir untuk mempersiapkan teknisi yang kompeten di bidang EV dan hybrid. Peserta akan mempelajari arsitektur sistem EV, manajemen baterai, high voltage safety, dan teknik diagnostic khusus kendaraan elektrifikasi.',
                'icon'               => 'electric_car',
                'modules'            => [
                    'Pengantar Teknologi EV & Hybrid',
                    'Arsitektur Sistem Propulsi Listrik',
                    'Baterai Lithium-Ion & Battery Management System (BMS)',
                    'High Voltage Safety & Prosedur Kerja Aman',
                    'Sistem Regenerative Braking & Charging',
                    'EV Diagnostic & Troubleshooting',
                ],
                'learning_outcomes'  => [
                    'Bekerja dengan aman pada sistem high voltage kendaraan EV',
                    'Melakukan diagnostic dan troubleshooting kendaraan EV/Hybrid',
                    'Memahami cara kerja BMS dan sistem manajemen daya',
                    'Melaksanakan prosedur servis kendaraan EV sesuai SOP pabrikan',
                ],
                'target_participants' => [
                    'Teknisi Otomotif Berpengalaman',
                    'Engineer Otomotif',
                    'Karyawan Dealer/Workshop Resmi',
                ],
                'duration'           => '6 Hari',
                'level'              => 'Teknisi',
                'price_display'      => 'Rp 4.200.000',
                'is_featured'        => false,
                'is_active'          => true,
                'order'              => 2,
            ],

            // ── OIL & GAS ────────────────────────────────────────────────
            [
                'category_id'        => $cat('oil-gas-migas'),
                'title'              => 'H2S Safety & Awareness',
                'slug'               => 'h2s-safety-awareness',
                'description'        => 'Pelatihan keselamatan H2S (Hydrogen Sulfide) wajib bagi pekerja di area migas dan industri kimia.',
                'description_long'   => 'Hydrogen Sulfide (H2S) adalah gas beracun yang menjadi ancaman nyata di industri migas dan petrokimia. Program ini memberikan pengetahuan dan keterampilan praktis untuk mendeteksi, mencegah, dan merespons paparan H2S di lingkungan kerja.',
                'icon'               => 'warning',
                'modules'            => [
                    'Sifat & Bahaya Gas H2S',
                    'Deteksi H2S: Alat & Prosedur',
                    'Penggunaan Self-Contained Breathing Apparatus (SCBA)',
                    'Prosedur Evakuasi & Rescue dari Area H2S',
                    'Emergency Response Procedure (ERP) H2S',
                    'Regulasi & Standar Keselamatan H2S',
                ],
                'learning_outcomes'  => [
                    'Memahami sifat, bahaya, dan ambang batas aman H2S',
                    'Menggunakan detektor H2S dan SCBA dengan benar',
                    'Melaksanakan prosedur evakuasi dari area H2S',
                    'Melakukan rescue dasar pada korban paparan H2S',
                ],
                'target_participants' => [
                    'Semua Pekerja di Area MIGAS',
                    'Teknisi & Operator Petrokimia',
                    'HSE Officer Industri MIGAS',
                ],
                'duration'           => '2 Hari',
                'level'              => 'Operator',
                'price_display'      => 'Rp 2.500.000',
                'is_featured'        => true,
                'is_active'          => true,
                'order'              => 1,
            ],
            [
                'category_id'        => $cat('oil-gas-migas'),
                'title'              => 'Well Control & IWCF',
                'slug'               => 'well-control-iwcf',
                'description'        => 'Sertifikasi well control internasional (IWCF) untuk driller, toolpusher, dan engineer pengeboran migas.',
                'description_long'   => 'Program Well Control STC mempersiapkan peserta untuk menghadapi situasi darurat selama operasi pengeboran. Dengan simulator drilling terkini, peserta akan berlatih mengenali kick, melakukan shut-in, dan menerapkan kill procedure secara efektif sesuai standar IWCF internasional.',
                'icon'               => 'oil_barrel',
                'modules'            => [
                    'Dasar-Dasar Tekanan Formasi & Gradien Pori',
                    'Penyebab & Deteksi Dini Kick',
                    'Prosedur Shut-In Sumur (BOP Operation)',
                    'Kill Method: Driller\'s & Wait & Weight',
                    'Penggunaan Drilling Simulator',
                    'Regulasi & Dokumentasi Well Control',
                ],
                'learning_outcomes'  => [
                    'Mengidentifikasi tanda-tanda awal terjadinya kick',
                    'Melakukan shut-in sumur dengan prosedur yang benar',
                    'Menghitung dan mengeksekusi kill procedure',
                    'Mendapatkan sertifikasi IWCF Well Control',
                ],
                'target_participants' => [
                    'Driller & Assistant Driller',
                    'Toolpusher & Drilling Engineer',
                    'Mud Engineer & Completion Engineer',
                ],
                'duration'           => '5 Hari',
                'level'              => 'Spesialis',
                'price_display'      => 'Rp 8.500.000',
                'is_featured'        => false,
                'is_active'          => true,
                'order'              => 2,
            ],

            // ── WELDING ──────────────────────────────────────────────────
            [
                'category_id'        => $cat('welding-fabrikasi'),
                'title'              => 'Sertifikasi Welder SMAW 3G/4G',
                'slug'               => 'welder-smaw-3g-4g',
                'description'        => 'Sertifikasi juru las SMAW posisi 3G (vertikal) dan 4G (overhead) sesuai standar BNSP dan AWS D1.1.',
                'description_long'   => 'Program Welder SMAW STC adalah program unggulan yang telah menghasilkan ribuan welder bersertifikat. Dengan workshop welding berstandar industri dan instruktur berpengalaman, peserta akan menguasai teknik pengelasan SMAW di berbagai posisi dan siap menghadapi uji kompetensi.',
                'icon'               => 'hardware',
                'modules'            => [
                    'Teori Dasar Pengelasan & Metalurgi Las',
                    'Keselamatan Kerja Pengelasan (Welding Safety)',
                    'Teknik SMAW Posisi 1G & 2G (Dasar)',
                    'Teknik SMAW Posisi 3G (Vertikal)',
                    'Teknik SMAW Posisi 4G (Overhead)',
                    'Inspeksi Visual Las & Cacat Las (NDT Dasar)',
                ],
                'learning_outcomes'  => [
                    'Mengelas pelat baja karbon dengan proses SMAW di posisi 3G dan 4G',
                    'Memenuhi standar kualitas lasan AWS D1.1 dan ASME IX',
                    'Melakukan inspeksi visual hasil pengelasan',
                    'Mendapatkan sertifikasi Juru Las BNSP',
                ],
                'target_participants' => [
                    'Juru Las Pemula & Menengah',
                    'Teknisi Fabrikasi Logam',
                    'Lulusan SMK Teknik Las',
                ],
                'duration'           => '3 Minggu',
                'level'              => 'Teknisi',
                'price_display'      => 'Rp 5.500.000',
                'is_featured'        => true,
                'is_active'          => true,
                'order'              => 1,
            ],

            // ── LISTRIK & INSTRUMENTASI ──────────────────────────────────
            [
                'category_id'        => $cat('listrik-instrumentasi'),
                'title'              => 'PLC Programming & SCADA',
                'slug'               => 'plc-programming-scada',
                'description'        => 'Pelatihan pemrograman PLC (Siemens/Omron) dan sistem SCADA untuk teknisi otomasi industri.',
                'description_long'   => 'Otomasi industri adalah kompetensi masa depan yang sangat dibutuhkan. Program ini mengajarkan pemrograman PLC berbasis Ladder Diagram, Function Block, dan Statement List, serta integrasi dengan sistem SCADA untuk monitoring dan kontrol proses industri secara real-time.',
                'icon'               => 'memory',
                'modules'            => [
                    'Dasar-Dasar Sistem Kontrol & Otomasi Industri',
                    'Hardware PLC: Arsitektur & Wiring',
                    'Pemrograman Ladder Diagram (LD)',
                    'Pemrograman Function Block Diagram (FBD)',
                    'Komunikasi PLC: Modbus, Profibus, Ethernet/IP',
                    'SCADA System: Konfigurasi & HMI Development',
                ],
                'learning_outcomes'  => [
                    'Memprogram PLC Siemens S7 dan Omron CP series',
                    'Merancang dan mengkonfigurasi sistem SCADA sederhana',
                    'Melakukan troubleshooting sistem otomasi PLC',
                    'Mengintegrasikan PLC dengan sensor, aktuator, dan HMI',
                ],
                'target_participants' => [
                    'Teknisi Instrumentasi & Kontrol',
                    'Electrical Engineer',
                    'Teknisi Maintenance Pabrik',
                ],
                'duration'           => '10 Hari',
                'level'              => 'Teknisi',
                'price_display'      => 'Rp 4.800.000',
                'is_featured'        => true,
                'is_active'          => true,
                'order'              => 1,
            ],
            [
                'category_id'        => $cat('listrik-instrumentasi'),
                'title'              => 'Teknisi Panel Listrik & Wiring Industri',
                'slug'               => 'teknisi-panel-listrik-wiring',
                'description'        => 'Pelatihan instalasi, wiring, dan troubleshooting panel kontrol listrik industri sesuai standar PUIL.',
                'description_long'   => 'Panel listrik adalah jantung dari sistem kelistrikan industri. Program ini memberikan keterampilan praktis dalam merancang, memasang, dan memelihara panel kontrol industri mulai dari MCC (Motor Control Center), panel distribusi, hingga panel ATS/AMF.',
                'icon'               => 'electrical_services',
                'modules'            => [
                    'Dasar Kelistrikan Industri & PUIL 2011',
                    'Komponen Panel Listrik: MCCB, MCB, Kontaktor, Relay',
                    'Teknik Wiring & Terminasi Kabel',
                    'Instalasi Motor Control Center (MCC)',
                    'Pembacaan Wiring Diagram & Single Line Diagram',
                    'Troubleshooting Panel Listrik Industri',
                ],
                'learning_outcomes'  => [
                    'Membaca dan menginterpretasikan wiring diagram panel industri',
                    'Melakukan instalasi dan terminasi kabel panel dengan benar',
                    'Mengkonfigurasi dan mengoperasikan MCC',
                    'Melakukan troubleshooting gangguan pada panel listrik',
                ],
                'target_participants' => [
                    'Teknisi Listrik Industri',
                    'Electrician & Panel Builder',
                    'Maintenance Electrician',
                ],
                'duration'           => '7 Hari',
                'level'              => 'Teknisi',
                'price_display'      => 'Rp 3.500.000',
                'is_featured'        => false,
                'is_active'          => true,
                'order'              => 2,
            ],
        ];

        foreach ($programs as $data) {
            Program::updateOrCreate(['slug' => $data['slug']], $data);
        }

        $this->command->info('✅ Program seeded: ' . count($programs) . ' records.');
    }
}